# Generated by Django 4.2.16 on 2025-12-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_invoice_payout_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='lawyer',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Payout',
        ),
    ]
